name: release

on:
  push:
    tags:
      - "*"

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build UI
        run:  cd ui && yarn install && yarn build

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env
          echo 'GITHUB_USER=${{github.event.repository.owner.login}}' >> .release-env
          echo 'GITHUB_PROJECT=${{github.event.repository.name}}' >> .release-env

      - name: Release publish
        run: make release

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.event.repository.owner.login}}
          password: ${{secrets.GORELEASER_ACCESS_TOKEN}}

      - name: Push
        run: docker push -a ghcr.io/${{github.event.repository.owner.login}}/${{github.event.repository.name}}
