name: release

on:
  push:
    tags:
      - "*"

jobs:

  release:

    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Login (${{ env.REGISTRY }})
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GORELEASER_ACCESS_TOKEN }}

      - name: Build UI
        run:  cd ui && yarn install && yarn build

      - name: Setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' > .release-env

      - name: Release publish
        run: make release
